# 2020-11-25
# function: makeDotPlot

# Takes in a list of genes and a Seurat object,
# and retrieves the average gene expression for each group of cells, 
# as specified in group_by (and optionally in split_by)

# Paramteters:
# genes_list can be a vector of genes or a list of vectors.

makeDotPlot <- function(# Params for Seurat::DotPlot
                          seurat_object = ncx_full,  
                          genes_list,   
                          idents_use, 
                          group_by, 
                          split_by, 
                          scale = FALSE,
                        # Params for scaling and plotting
                          mode = c('genes_by_area', 'paired_areas') 
                                # paired-areas refers to genes by age in side by side areas.
                          scale_by = 'gene',
                        # Params for plotting and printing
                          color_scale = 'viridis',
                          group, 
                          area, 
                          title) {

  # 1. Make Seurat DotPlot -------------------------
  
  dotplot <- Seurat::DotPlot(object = seurat_object,
                           idents = idents_use,
                           features = genes_list,
                           group.by = group_by,
                           split.by = 'cell_type',
                           scale = scale,
                           cols =  "RdYlBu",
                           dot.min = 0.01)
        
  # 2. Use dotplot$data to get average gene expression for each group of cells -------------------

      x <- dotplot$data %>%
          separate(id, c('id_1', 'id_2'), remove = FALSE)
  
      ## Clean up x$data for manipulations below (scaling, ggplot)

      # For normal DotPlot  
        # id_1 = area
        # id_2 = cell_type (only one type)
        
        # For or PFC/V1 (type: paired)
        # id_1 = age
        # id_2 = area
      
        # A tibble: 114 x 7
        # avg.exp pct.exp features.plot id       id_1  id_2  avg.exp.scaled
        # <dbl>   <dbl> <fct>         <fct>    <fct> <chr>          <dbl>
        # 1   0.652    23.7 NR2F1         motor_rg motor rg           -0.428 
        # 2   5.71     82.5 NFIA          motor_rg motor rg            1.74  
        # 3   0.609    20.9 ZBTB18        motor_rg motor rg           -0.497 
        # 4   3.86     71.5 TCF4          motor_rg motor rg            1.35  
        # 5   3.08     54.2 SOX11         motor_rg motor rg            1.13  
        # 6   1.03     34.3 NFIX          motor_rg motor rg            0.0249
        # 7   4.29     74.5 NFIB          motor_rg motor rg            1.46  
        # 8   2.67     54.9 HMGB2         motor_rg motor rg            0.982 
        # 9   0.478    19.6 ZNF462        motor_rg motor rg           -0.739 
        # 10   0.344   16.4 ZIC2         motor_rg motor rg           -1.07  
        #  … with 104 more rows
      
      # type: normal
          if(any(x$id_1 == 'pfc')) { 
            x %<>% mutate(id_1 = factor(id_1, levels = levels(ncx_full@meta.data$area))) 
          }
        
      # type: paired
         if(any(str_detect(x$id_1, '18'))) {
           x %<>% mutate(id_1 = as.numeric(id_1)) 
         }
         
         if(any(x$id_2 == 'pfc')) { 
           x %<>% mutate(id_1 = factor(id_1, levels = levels(ncx_full@meta.data$area))) 
         }
         
         if(any(str_detect(x$id_1, '[:digit:]+'))) {
           x %<>% mutate(id_1 = as.numeric(id_1)) 
         }
           
  
  # 3. SCALING ----------------------------------------------------
  
     # Scale average expression values by individual.
     message('Scaling. \n ')
     
       if(scale_by == 'gene') {
          cat('Scaling each gene across each group (column-wise).\n')
          x %<>% group_by(features.plot) %>%
            mutate(scaled_exp = scale(avg.exp, center = TRUE)) %>%
            ungroup
       } 
      
      # mode == 'paired'
      if(scale_by == 'id_2') { 
       cat('Scaling each gene within each id_2.\n')
       # Scale average expression values by individual.
       x %<>% group_by(id_2, features.plot)  %>%
         mutate(scaled_exp = scale(avg.exp, center = TRUE)) %>%
         ungroup
     } else {
          cat('Scaling each gene within each id_1.\n')
          # Scale average expression values by individual.
          x %<>% group_by(id_1, features.plot)  %>%
            mutate(scaled_exp = scale(avg.exp, center = TRUE)) %>%
            ungroup
        }
    
    # END SCALING
     
  # 4. Use x$data to make own ggplot dotplot. ---------------------------------------
  
   message('n_genes: \n'); cat(n_genes = n_distinct(x$features.plot))
   
   message('Max size: \n'); cat(max_size = 500 / n_genes)
   
   message('Making ggplot \n x: \n')
  
      # PFC / V1 DotPlots across ages. (side-by-side areas) ----------------------------------------
        
        if(mode == 'paired-areas') {
          
          # id_1 = area/region; 1 = pfc ; 6 = v1
          # id_2 = age
          
          x %<>% dfilter(id %>% str_detect('pfc|v1') & 
                         !(id_2 %>% str_detect('14|25')))

          x %<>% unite(gene_region, 'features.plot', 'id_1', remove = FALSE)

          x %<>% bind_rows(data.frame(features.plot = x$features.plot, 
                                 gene_region = paste0(x$features.plot, '_NA'), 
                                 scaled_exp = NA)) %>%
             mutate(x_label = case_when(gene_region %>% str_detect('_1') ~ as.character(features.plot),
                                                                    TRUE ~ ''))
          
            ## Prepare for clustering
              ## Group rows by gene and age, then get the diff in expression between pfc and v1.
              ## id_1 = area/region; 1 = pfc ; 6 = v1
          
            x %<>% group_by(features.plot, id_2) %>% 
               mutate(diff = scaled_exp[id_1 == 1] - scaled_exp[id_1 == 6]) %>% ungroup %>%
              
              dfilter(id_1 == 1) %>% 
                select(features.plot, id_2, diff) %>% 
                spread(key = id_2, value = diff)
        }
  
     # General DotPlots: genes in columns, areas in rows.  -----------------------------------------
   
         if(mode == 'genes_by_area'){
               
           ## Prepare for clustering
              # Spread
           
            # id_1 = area
             x %>% 
              select(features.plot, id_1, scaled_exp) %>% 
               spread(key = id_1, value = scaled_exp)
         }
   
   
  # 5. CLUSTER GENES ----------------------------------------------------------
  # by similarity

           dist <- x  %>%  column_to_rownames('features.plot') %>% 
                      dist(diag = TRUE, upper = TRUE)
           
           genes_hclust <- hclust(dist)
           
           x %<>% mutate(features.plot = features.plot %>% 
                           factor(levels = genes_hclust$labels[genes_hclust$order]),
                          id = as_factor(as.character(id)))
                        
           x %<>% arrange(features.plot, id_1, id_2) %>%
                   mutate(gene_region = as_factor(gene_region))
  print(x)
  
  # 6. GGPLOT -------------------------------------------------
  
  dotplot <- ggplot(x) + ggtitle(title) +
  
            geom_point(aes(x = gene_region, y = id_2, 
                 colour = scaled_exp,
                 # alpha = scaled_exp,
                 size = pct.exp),
                 shape = 16) +
    
    # Color scale . . . . . . . . . . . . . . . . 

      if(color_scale == 'viridis') {  
        
        dotplot <- dotplot + 
          scale_colour_gradientn(colours = viridis(n = 100, option = 'plasma', end = 0.95),
                                 na.value = "white")
        }
  
      if(color_scale == 'red_yellow_blue'){
        
        dotplot <- dotplot + 
                      scale_colour_gradientn(colours = rev(heatmap.colors),
                                         # TODO Maybe keep high yellow, low blue gradient.
                                         #values = c(0, 0.3, 1),
                                         # breaks = c(0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9),
                                         # limits = c(0.01, 0.9),
                                         na.value = "white")
      }
  
    #  Refine plot . . . . . . . . . . . . . . . . 
    
    dotplot <- dotplot +
    
      # scale_x_discrete(labels = x$x_label) +
      # scale_alpha(range = c(0.5, 0.9)) +
      scale_size_area(limits = c(0, 100), max_size = max_size) +

      guides(size = guide_legend(direction = "vertical")) +
      
      theme_void() +
      theme(plot.title = element_text(size = 9), 
            text = element_text(size = 5, colour = 'grey30'),
            axis.text.x = element_text(size = 5, angle = 45, vjust = 1, hjust = 1),
            axis.text.y = element_text(size = 5, angle = 0, hjust = 1),
            axis.title = element_blank(),
            legend.position = 'right',
            legend.key.size = unit(0.1, units = 'in'))
        
} # END makeDotPlot ---------------------------------------------


heatmap.colors <- 
  c("Vermilion" = "#DF4619",
    "Flame"="#E45A17",
    "Marigold"="#F4AD39",
    "Naples Yellow"="#FAD85F",
    "Key Lime"="#F0FD8C",
    "Light Green"="#ADF196",
    "Maximum Blue Green"="#25BFC6",
    "Pacific Blue"="#21AFCB",
    "Blue NCS"="#1A90C1")
