---
title: 'Constellation Plots: Neocortex Excitatory: By Ages (for reviews)'
date: 2021-03-03
output: html_document
---

```{r}
knitr::opts_knit$set(progress = TRUE, verbose = TRUE)
```

```{r}
ncx.exn@meta.data %>% count(individual)
```

```{r call-buildConstellationPlot}

# Neocortex excitatory (271k) used originally to make the 'cell types by area' constellation plot.
# This object was saved when making the 'cell types by cluster' constellation plot,
# but has everything we need to make dfs.
loadData <- function() {
  
  x <- read_rds('../out_intermediate/ncx_exn_byCluster/dfs_and_objects_for_constellationPlot_ncx_exn_byCluster.rds')
  
  names(x) <- c('cells_cl_df', 'cluster_colors', 'cl', 'cl_numeric', 'cl_center_df', 'reductions')
   x$cells_cl_df %<>%  
                      rename(cell_type_area = "cell.type.area") %>%
                      rename(cell_type = "cell.type") %>% 
                      rename(cell_name = "cell.name") %>%
     expandMetadata() %>%
                      set_rownames(.$cell_name)
    
    cell_names <- x$cells_cl_df$cell_name
    
    x$cl <- x$cells_cl_df$cell_type_area %>% purrr::set_names(nm = cell_names)
    x$cl_numeric <- as.numeric(as.factor(x$cl)) %>% purrr::set_names(nm = cell_names)
    x$cells_cl_df$cl_id <- x$cl_numeric
  # TODO Not converting gw16 and gw19_2 because expandMetadata needs to be fixed to include those ages.
  # WARNING: Input `stage` is `fct_collapse(...)`.Unknown levels in `f`: gw16, gw19_2
  return(x)
}
# --------

x$cluster_colors %<>% rename(clade = 'celltype')
x$cells_cl_df %<>% select(-cl_id, -cluster_label) %<>% 
  rename(cluster_label = 'cell.type.area')

```

## 2. Make constellation plot.

Call `buildConstellation.Rmd`, which has all the steps required to make dfs and plot.

Takes arguments: - cells.cl.df - groups.col - colors.use - rd.dat

```{r}
'../R/buildConstellation.Rmd'

rmarkdown::render(input = "../R/buildConstellation.Rmd", 
                  params = list(cells.cl.df = x$cells_cl_df, 
                                rd.dat = x$reductions, 
                                groups.col = "cluster_label", # renamed from cell.type.area 
                                colors.use = x$cluster_colors,
                                n.pcs = 20,
                                run.knn = FALSE,
                                k = 15,
                                out.dir = '../out',
                                frac.th = 0.05,
                                cl = x$cl,
                                cl.numeric = x$cl_numeric)
)

```

## Split by stages

1.  Clean up metadata using `expandMetadata`.

This adds a colum `stage`, which groups ages into early, middle, late.

2.  Filter cells from each stage.

```{r}
early <- list()
early$cells_cl_df <- x$cells_cl_df %>% filter(stage == "early") %>% set_rownames(.$cell.name)
# 11,208

early$reductions$umap <- x$reductions$umap[early$cells_cl_df$cell.name, ]
early$reductions$pca <- x$reductions$pca[early$cells_cl_df$cell.name, ]

early$cl <- early$cells_cl_df$cluster_label %>% set_names(rownames(early$cells_cl_df))
early$cl_numeric <- as.numeric(as.factor(early$cl)) %>% set_names(rownames(early$cells_cl_df))

rmarkdown::render(input = "../R/buildConstellation.Rmd", 
                  params = list(cells.cl.df = early$cells_cl_df, 
                                rd.dat = early$reductions, 
                                groups.col = "cluster_label", # renamed from cell.type.area 
                                colors.use = x$cluster_colors,
                                n.pcs = 20,
                                run.knn = TRUE,
                                k = 15,
                                out.dir = '../out',
                                frac.th = 0.05,
                                cl = early$cl,
                                cl.numeric = early$cl_numeric)
)

```

Generalized form:

```{r}

x$cells_cl_df %>% dplyr::count(stage)

x$cells_cl_df %>% dplyr::count(individual)






getReductions <- function(object, stage_object) {
  cells_cl_df <- stage_object
  cell_names <- cells_cl_df$cell_name
  print(cell_names)
  reductions <- object$reductions %>% map(~.[ cell_names, ])
  
  cl <- cells_cl_df$cell_type_area %>% set_names(cell_names)
  cl_numeric <- as.numeric(as.factor(cl)) %>% set_names(cell_names)
  return(lst(cells_cl_df,reductions, cl, cl_numeric))
  }

a <- loadData()
split_stages <- a$cells_cl_df %>% split(.$stage) %>% map(~ getReductions(a, .))

split_stages %>% map(~ rmarkdown::render(input = "../R/buildConstellation.Rmd", 
                      params = list(args_list = ., 
                                
                                groups.col = "cell_type_area", # renamed from cell.type.area 
                                colors.use = x$cluster_colors,
                                n.pcs = 20,
                                run.knn = TRUE,
                                k = 15,
                                out.dir = '../out',
                                frac.th = 0.05)))
#  ---
  split_stages$early %>% glimpse

split_stages %>% enframe %>% pmap(~ rmarkdown::render(input = "../R/buildConstellation.Rmd",
                                  params = list(name = ..1, args_list = ..2, 
                                  groups.col = "cell_type_area", # renamed from cell.type.area 
                                  colors.use = a$cluster_colors,
                                  max_size = 25,
                                  run.knn = TRUE,
                                  n.pcs = 20,
                                  k = 15,
                                  frac.th = 0.05,
                                  out.dir = '~/Dropbox/ARK_lab/second-trimester/2nd Trimester Areas Paper/revisions/constellation/'
                                  )))


```

With R script only (as function):
```{r}
source("../R/buildConstellation.R")

split_stages$late %>% buildConstellation(args_list = .,
                                         groups.col = "cell_type_area",
                                         # renamed from cell.type.area 
                                        colors.use = x$cluster_colors,
                                        run.knn = TRUE,
                                        k = 15,
                                        n.pcs = 20,
                                        frac.th = 0.05,
                                        out.dir = '../out'
                                      )

# All 3 stages
constellation_output <- split_stages %>% map(~ buildConstellation(args_list = .,
                                         groups.col = "cell_type_area",
                                         # renamed from cell.type.area 
                                        colors.use = x$cluster_colors,
                                        run.knn = TRUE,
                                        k = 15,
                                        n.pcs = 20,
                                        frac.th = 0.05,
                                        out.dir = '../out'
                                        ))

# TODO 2021-03-04
# - Save to Dropbox
# - Add stage to filename; remove time
# - Remove CSV save (node dodge)
# - Make scratchh hicat .R
# - Node size smaller?
# - Add oRG annotations
# - Do only between RG/Neurons/IPCs.
```
