---
title: "Making shared-gene heatmaps from Sankey plot"
date: 2020-10-27
output: html_notebook
---

Need:

```{r}
library(pacman)
p_load(tidyverse)
p_load(glue)
```

.rds file with shared genes between cell groups

```{r}
pairs.norm <- read_rds("../2020-10-22/sankey_markers_pairs_exnLineage.rds")

pairs
```

Split groups

```{r}
comparisons.inter <- tribble(
                  ~celltype_1, ~celltype_2,

                        "rg",  "neuron",
                        "rg",  "ipc",
                        "ipc", "neuron"
                )

comparisons.intra <- tribble(
                  ~celltype_1, ~celltype_2,

                        "rg",  "rg",
                        "ipc",  "ipc",
                        "neuron", "neuron"
                )



gvis.df.inter <-  purrr::pmap(.l = comparisons.inter, 
                              .f = ~ pairs.norm %>% select(-genes) %>%
                # mutate(n = as.integer(n)) %>%  [not sure if necessary]
                                filter(item1 %>% str_detect(..1) & 
                                         item2 %>% str_detect(..2)) %>% 
                                  filter(! item2 %>% str_detect("all|shared")) %>%
                                    arrange(celltype_source, stage_source, region_source, 
                                            stage_target, region_target) %>% 
                                      mutate(item2 = str_remove(item2, "_unique"))
                  ) %>%
                    tibble(item1_item2 = pmap_chr(.l = comparisons.inter, 
                                                  ~ glue(..1, ..2, .sep = "_to_")), df = .)

gvis.df.intra <- purrr::pmap(.l = comparisons.intra, 
                              .f = ~ pairs.norm %>% select(-genes) %>%
                # mutate(n = as.integer(n)) %>%  [not sure if necessary]
                                filter(item1 %>% str_detect(..1) & 
                                         item2 %>% str_detect(..2)) %>% 
                                  filter(! item2 %>% str_detect("all|shared")) %>%
                                    arrange(celltype_source, stage_source, region_source, 
                                            stage_target, region_target) %>% 
                                      mutate(item2 = str_remove(item2, "_unique"))
                  ) %>%
                    tibble(item1_item2 = pmap_chr(.l = comparisons.intra, 
                                                  ~ glue(..1, ..2, .sep = "_to_")), df = .)
```

Actually make heatmap / dotplot

```{r}
gvis.df.inter$heatmaps <- gvis.df.inter$df %>% map(.x = ., .f = buildHeatmap)
gvis.df.intra$heatmaps <- gvis.df.intra$df %>% map(.x = ., .f = buildHeatmap)

pmap(gvis.df.intra, 
      .f = ~ saveWidget(widget = ..3,
                                    file = paste0("../out/sankey_quantification_heatmap_", ..1, ".html"),
                                    title = ..1, 
                                    selfcontained = TRUE)
)

p_load(sp) #pby.colors
p_load(htmlwidgets)
p_load(htmltools)
p_load(manipulateWidget)
p_load(magrittr)
    
# 2020-10-27 Not working:
# combineWidgets(heatmaps, nrow = 1) %>% saveWidget(file = "../2020-10-22/sankey_quantification_heatmaps.html",
#                                                    title = "sankey_sharedGenes_heatmap", selfcontained = TRUE)
  
combineWidgets(heatmaps$rg$all, heatmaps$neuron$all, heatmaps$ipc$all, nrow = 1)

# TODO use index as title of plot (eg. rg early)
# TODO separate parietal from motor, somato. or motor, somato, parietal


```

```{r fxn-buildHeatmap}


# df <- gvis.df.inter$df[[1]] 

buildHeatmap <- function(df) {

  df.wide <- pivot_wider(df, id_cols = item1, names_from = item2, values_from = n_norm) %>% 
                column_to_rownames("item1")

  df %<>% ungroup %>%  mutate_if(.predicate = is.factor, .funs = fct_drop)

  # Colors for sidebar
  # . . . . . . . . . .
  row_colors <- rownames(df.wide) %>% tibble(item1 = .) %>% 
                                     left_join(df %>% select(item1, ends_with("source"))) %>% distinct

  col_colors <- colnames(df.wide) %>% tibble(item2 = .) %>% 
                                     left_join(df %>% select(item2, ends_with("target"))) %>% distinct
  
  colors.use <- map(list(row = row_colors, col = col_colors), .f = fnColors)
      # colors.df <- row_colors
      # colors.df <- col_colors
  
      fnColors <- function(colors.df) {
  
                      vars.colors = colors.df %>% select(contains(c("region_", "stage_")), 
                                                            -contains("color"))
                      
                      vars.levels = map(.x = colors.df %>% select(starts_with(c("region_", "stage_"))),
                                   .f = levels)
                      
                      colors.region <- colors.df %>% select(starts_with("color.region")) %>% 
                                    unlist(use.names = FALSE) %>% unique %>% 
                                      set_names(value = vars.levels[[1]])
                      
                      colors.stage <- c("grey20", "grey40", "grey60") %>% set_names(vars.levels[[2]])
                      
                      
                      palette = c(colors.region, colors.stage)

                      
                      return(list(vars.colors = vars.colors, 
                                  palette = palette)
                             )
                    }

  heatmap <- heatmaply(x = df.wide,

                    node_type = 'scatter', 
                    point_size_mat = df.wide,
                    point_size_name = "% markers shared",
                    scale = "none",

                    # Colv = "Rowv", show_dendrogram = c(FALSE, FALSE), k_row = 3,
                    
                      
                    row_side_colors = colors.use$row$vars.colors,
                    
                    row_side_palette = colors.use$row$palette,
                    
                    col_side_colors = colors.use$col$vars.colors,
                    
                    col_side_palette = colors.use$col$palette,

                    
                    # col_side_colors = df %>% select(item2, ends_with("target")) %>% 
                    #                              distinct %>% 
                    #                           select(contains(match = c("region", "stage"))),
                    # 
                    #   col_side_palette = df$color.region_target,
                    
                    scale_fill_gradient_fun = scale_colour_gradientn(
                    
                                                  na.value = "white",
                                                  
                                                  colors = bpy.colors(n = 100, alpha = 0.9),
                                                  
                                                  values = c(0, 0.3, 1),
                                                  
                                                  breaks = c(0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9),
                                                  
                                                  limits = c(0.01, 0.9),
                                                  
                                                  labels = c(0, 0.05, 0.1, 0.25, 0.5, 0.75, 0.9) %>% 
                                                             as.character,
                                                  
                                                  name = "fraction of markers shared",
                                                  
                                                  oob = scales::squish
                                                  
                                                  ),
                    
                    heatmap_layers = list(scale_size_binned_area(# max_size = 10,
                    
                                          # n.breaks = 100,
                                          
                                          breaks = c(0.0, 0.049, seq(0.05, 0.9, by = 0.1)),
                                          
                                          limits = c(0.01, 0.9),
                                          
                                          oob = scales::censor
                                          
                                          ))
                    )

# Resize widget so to a specific width/height and turn off filling entire browser.
# <https://stackoverflow.com/questions/47921757/how-to-resize-html-widget-using-savewidget-in-htmlwidgets-r>
heatmap$sizingPolicy$defaultWidth <- 1000
heatmap$sizingPolicy$defaultHeight <- 700

heatmap$sizingPolicy$viewer$fill <- TRUE
heatmap$sizingPolicy$browser$fill <- FALSE

# Remove "row / col side colors text"
heatmaps$x$layout$annotations[c(1,2)] <- NULL

return(heatmap)

}

```
