```{r}
wb.small <- read_rds("../data/wholebrain_v3_small68k.rds")
```


# fx: featurePlotNice

```{r}
featurePlotNice <- function(seurat.object = seurat.object,
                            version = v3,
                            integrated = FALSE,
                            exp.df = data,
                            gene = SOX2,
                            cap = 4,
                            pt.size = 0.01, pt.size.grey = 0.01,
                            alpha.group = 0.7, alpha.grey = 0.5,
                            begin = 0,
                            end = 1,
                            color.scale = "viridis",
                            legend.pos = "none"
                            ) {

  gene <- enquo(gene)
  exp.df <- enquo(exp.df)
  version <- enquo(version)

  print(quo_text(version))
  
  

  if(quo_text(version) == "v2") {

  umap.embeddings <- seurat.object@dr$umap@cell.embeddings %>%
    data.frame %>% rownames_to_column("cell.name")

  exp.df <- seurat.object %>% slot(quo_text(exp.df))

  }

  if(quo_text(version) == "v3") {

        umap.embeddings <- seurat.object@reductions$umap@cell.embeddings %>%
          data.frame %>% rownames_to_column("cell.name")

        if(integrated == FALSE) {
          exp.df <- seurat.object@assays$RNA %>% slot(quo_text(exp.df))
        }

        if(integrated == TRUE) {
          exp.df <- seurat.object@assays$integrated %>% slot(quo_text(exp.df))
                                                             
        }

  }
  
  
  
 exp.df <- exp.df[as_name(gene), ] %>% as.data.frame %>%
   set_colnames("exp") %>%
   rownames_to_column("cell.name")
   
   head(exp.df) %>% print

   head(umap.embeddings) %>% print

   meta <- seurat.object@meta.data 
   # %>% rownames_to_column ("cell.name")
   head(meta) %>% print
   
   umap.metadata <- left_join(meta, umap.embeddings)
   umap.metadata %>% head %>% print
   
 # gene.text <- quo_text(gene)

 # df <- exp.df %>% dplyr::select(cell.name, !!gene) %>%
   
 df <- left_join(umap.metadata, exp.df , by = "cell.name") %>% arrange(exp)
 
 print(head(df))
 df <- df %>% mutate(exp.cap = case_when(exp > cap ~ cap,
                                              TRUE ~ exp)
              )
 
 head(df)

 p <- ggplot(df) +

   # Background cells
   geom_point(data = dplyr::filter(df, exp <= 0.1),
              aes(UMAP_1, UMAP_2),
              colour = "grey80", size = pt.size.grey,
              alpha = alpha.grey, shape = 16) +

   # Cells with non-zero expression of the gene.
   geom_point(data = dplyr::filter(df, exp > 0.1),
              aes(UMAP_1, UMAP_2,
                  colour = exp.cap),
              size = pt.size, 
              alpha = alpha.group,
              shape = 16) +

 # geom_vline(xintercept = quan)

 ggtitle(as_name(gene)) +
   
   scale_color_viridis_c(option = "magms",
                         begin = begin,
                         end = end, 
                         name = "expression",
                         guide = guide_colourbar(ticks = TRUE)) +
                         # breaks = seq(0, 6, by = 1)) +
   
   # scale_alpha(range = c(0.3, 0.8))
   # guides(alpha = FALSE) +
   
   theme(legend.position = legend.pos,
         legend.key.width = unit(0.25,"cm"),
         # legend.text = element_blank(),
         legend.title = element_text(size = 6),
         panel.grid = element_blank(),
         axis.title = element_blank(),
         axis.text = element_blank(),
         axis.ticks = element_blank(),
         panel.background = element_blank(),
         axis.line = element_blank(),
         panel.border = element_blank(),
         aspect.ratio = 1
   )

 return(p)
}

## Example

featurePlotNice(seurat.object = wb.small,
                exp.df = data,
                gene = SOX2,
                legend.pos = "right",
                cap = 3.8,
                pt.size = 0.25,
                pt.size.grey = 0.2,
                alpha.group = 0.7,
                alpha.grey = 0.3,
                begin = 0,
                end = 0.95)


```

# fx: histogramExpression 
```{r}
histogramExpression <-  function(gene = SOX2, seurat.object = seurat.object,
                                integrated = FALSE, version = v3, exp.df = data) {

  gene <- enquo(gene)
  version <- enquo(version)
  exp.df <- enquo(exp.df)
  # gene <- quo(SOX2)

if(quo_text(version) == "v2") {

  gene.exp <- seurat.object@data[quo_text(gene), ] %>%
    as.data.frame() %>% setNames(quo_text(gene))

    }

if(quo_text(version) == "v3") {

      if(integrated == FALSE) {
        gene.exp <- seurat.object@assays$RNA %>% slot(quo_text(exp.df)) %>%
          # Gene names are rows in @data.
          .[quo_text(gene), ] %>%
          as.data.frame() %>% setNames(quo_text(gene))
      }

      if(integrated == TRUE) {
        gene.exp <- seurat.object@assays$integrated %>% slot(quo_text(exp.df)) %>%
          .[quo_text(gene), ] %>%
          as.data.frame() %>% setNames(quo_text(gene))
      }

}

  print(gene.exp %>% str)

  max.gene <- gene.exp %>% pull(!!gene) %>% max
  print(max.gene)

  p <-  ggplot(gene.exp %>% dplyr::filter(!!gene > 0.1 )) +
                geom_histogram(aes(x = !!gene), fill = "grey50", bins = 100, alpha = 0.5) +
                scale_x_continuous(breaks = seq(0, max.gene, by = 0.5)) +
                theme_minimal()  +
                theme(title = element_blank(),
                      axis.title = element_blank(),
                      axis.text = element_text(size = 5, angle = 45)
                      )
  
  return(p)
}

## Example

histogramExpression( seurat.object = wb.small,
                     gene = SOX2, 
                     exp.df = data)

```


# fx: FeatPlotHist
```{r}
featPlotHist <- function(seurat.object,
                         exp.df = data,
                         gene = SOX2,
                         alpha.group = 0.7,
                         alpha.grey = 0.3,
                         pt.size.grey = 0.2,
                         pt.size = 0.3,
                         cap = 5,
                         legend.pos = "right",
                         version = v3,
                         integrated = FALSE,
                         begin = 0,
                         end = 0.95) {

  gene <- enquo(gene)
  exp.df <- enquo(exp.df)
  version <- enquo(version)

  p1 <- featurePlotNice(seurat.object = seurat.object,
                        integrated = integrated,
                        exp.df = !!exp.df,
                        gene = !!gene,
                        legend.pos = legend.pos,
                        cap = cap,
                        pt.size = pt.size,
                        pt.size.grey = pt.size.grey,
                        alpha.group = alpha.group,
                        alpha.grey = alpha.grey,
                        begin = begin,
                        end = end,
                        version = !!version)
  

  p2 <- histogramExpression(!!gene, seurat.object = seurat.object,
                            integrated = integrated, version = !!version, exp.df = !!exp.df)

  # print(grid.arrange(p1, p2, ncol = 2, nrow = 1))
  # print(p1 + annotation_custom(ggplotGrob(p2), xmin = 1, xmax = 3,
  #                                       ymin = -0.3, ymax = 0.6)
  # )

  print(ggdraw() +
          draw_plot(p1) +
          draw_plot(p2, x = 0 , y = 0.7, 
                    width = 0.3, height = 0.25)
  )
  
}

## Example

fPlots <- list(featPlotHist(wb.small, cap = 3.75)
               featPlotHist(gene = SATB2, wb.small, cap = 3.5, begin = 0, end = 0.7, alpha.grey = 0.3, alpha.group = 0.7)
               featPlotHist(seurat.object = wb.small, gene = VIM, cap = 5.5)
               featPlotHist(gene = EOMES, seurat.object = wb.small, cap = 3.25)
)

plot_grid(plotlist = fPlots)

featPlotHist()
## Example 2


```




```{r}
genes <- c(SOX2, 
           SATB2, BCLB11, NEUN, TBR1,
           PPP1R17, TBR2)

makePlot <- function(gene, cap) {
  
                gene = enquo(gene)
                
                featPlotHist(gene = !!gene,
                             cap = cap,
                             seurat.object = wb.small, 
                             begin = 0, end = 0.95,
                             alpha.grey = 0.3, alpha.group = 0.7)
  
}

makePlot(gene=SOX2, cap = 3.9)

  
genes %>% lapply(featPlotHist(gene = ., seurat.object = wb.small)) %>% plot_grid(plotlist = .)

fPlots <- list(featPlotHist(wb.small, cap = 3.8, begin = 0, alpha.grey = 0.3, alpha.group = 0.7),
               featPlotHist(gene = SATB2, wb.small, cap = 3.5, begin = 0, alpha.grey = 0.3, alpha.group = 0.7)
)

fPlots[[3]] <- featPlotHist(seurat.object = wb.small, gene = VIM, cap = 5.5)


cowplot::plot_grid(plotlist = fPlots)
```

```{r}
makePlot(gene = AQP4, cap = 4.5)

makePlot(gene = HES1, cap = 5)

makePlot(gene = PPP1R17, cap = 4)

makePlot(gene = FOXG1, cap = 3.25)

makePlot(gene = RBFOX3, cap = 2.7)

makePlot(gene = SST, cap = 5)
makePlot(gene = CALB2, cap = 4)
makePlot(gene = CCK, cap = 5.5)
```

# Whole brain: region markers by cell type
For each cell type, get the top marker genes for each area.

# Read-in cell-type/areal marker genes
```{r}
dir <- "~/Dropbox/2ndTrimester/tbls/wholebrain_celltype_area_markers/"
files <- paste0(dir, list.files(dir))

# Use read.delim bc 1st column is rownames (tidyr functions don't work)
markers <- lapply(files, read.delim)
```

For each cell type, get the top marker genes for each area.

## Astrocytes
```{r}
markers[[1]] %<>% separate(cluster, c("celltype", "area"))

markers[[1]] %<>% mutate(gene.ratio = pct.1 / pct.2,
                        gene.score = avg_logFC * gene.ratio)


# https://stackoverflow.com/a/27766224 slice_max

top.markers <- markers[[1]] %>% group_by(area) %>% slice_max(order_by = gene.score, n = 5)

fPlots$astro <- top.markers$gene %>% lapply(function(x) { makePlot(gene = !!sym(x), 
                                                         cap = 4)
}
)


# https://stackoverflow.com/questions/39736655/plot-over-multiple-pages

m1 <- marrangeGrob(fPlots$astro, nrow=4, ncol=5)
names(m1) <- seq(1:length(m1))

for(i in names(m1)) {
  ggsave(plot = m1[[i]], 
         filename = paste0("../out/astrocyte_markers_", i, ".png"),
         device = "png",
         width = 45, height = 30, units = "in")
}


grid_arrange
ggarrange()
```

## Neurons
```{r}
markers[[6]] %<>% separate(cluster, c("celltype", "area")) %>% 
                      mutate(gene.ratio = pct.1 / pct.2,
                             gene.score = avg_logFC * gene.ratio)

top.markers <- list()
top.markers$neurons <- markers[[6]] %>% 
                        group_by(area) %>% 
                          slice_max(order_by = gene.score, n = 5)

fPlots$neurons <- top.markers$neurons$gene %>% 
                    lapply(function(x) { 
                      
                      makePlot(gene = !!sym(x), 
                               cap = 4)
                    }
                    )

m1 <- list()
m1$neurons <- marrangeGrob(fPlots$neurons, nrow=4, ncol=5)

names(m1$neurons) <- seq(1:length(m1$neurons))

for(i in names(m1$neurons)) {
  ggsave(plot = m1$neurons[[i]], 
         filename = paste0("../out/neuron_markers_", i, ".png"),
         device = "png",
         width = 45, height = 30, units = "in")
}
```

## Radial glia
```{r}
markers[[9]] %<>% separate(cluster, c("celltype", "area")) %>% 
                      mutate(gene.ratio = pct.1 / pct.2,
                             gene.score = avg_logFC * gene.ratio)

top.markers <- list()
top.markers$rg <- markers[[9]] %>% 
                        group_by(area) %>% 
                          slice_max(order_by = gene.score, n = 5)

fPlots$rg <- top.markers$rg$gene %>% 
                    lapply(function(x) { 
                      
                      makePlot(gene = !!sym(x), 
                               cap = 4)
                    }
                    )

m1 <- list()
m1$rg <- marrangeGrob(fPlots$rg, nrow=4, ncol=5)

names(m1$rg) <- seq(1:length(m1$rg))

for(i in names(m1$rg)) {
  ggsave(plot = m1$rg[[i]], 
         filename = paste0("../out/radialglia_markers_", i, ".png"),
         device = "png",
         width = 45, height = 30, units = "in")
}
```

## Dividing
```{r}
df <- markers[[2]]
celltype <- "dividing"

df %>% separate(cluster, c("celltype", "area")) %>% 
                      mutate(gene.ratio = pct.1 / pct.2,
                             gene.score = avg_logFC * gene.ratio)

top.markers <- list()
top.markers[[celltype]] <- markers[[9]] %>% 
                        group_by(area) %>% 
                          slice_max(order_by = gene.score, n = 5)

fPlots$rg <- top.markers$rg$gene %>% 
                    lapply(function(x) { 
                      
                      makePlot(gene = !!sym(x), 
                               cap = 4)
                    }
                    )

m1 <- list()
m1$rg <- marrangeGrob(fPlots$rg, nrow=4, ncol=5)

names(m1$rg) <- seq(1:length(m1$rg))

for(i in names(m1$rg)) {
  ggsave(plot = m1$rg[[i]], 
         filename = paste0("../out/radialglia_markers_", i, ".png"),
         device = "png",
         width = 45, height = 30, units = "in")
}
```

```{r}
p_load(cowplot)

featPlotHist(wb.small, cap = 3.9, begin = 0, alpha.grey = 0.3, alpha.group = 0.5)

wb.small@assays$RNA@data["SOX2", ] %>% as.data.frame() %>% setNames("SOX2")
```
```

