---
title: "Get GO & TF Annotations"
date: 2020-11-25
output: 
  bookdown::html_document2:
    fig_caption: yes
---

```{r}
p_load(biomaRt)
# listMarts()

ensembl <- useMart("ensembl")
ensembl <- useDataset("hsapiens_gene_ensembl", mart = ensembl)

# listDatasets(ensembl)
# listAttributes(ensembl) %>% filter(! name %>% str_detect("homolog"))

# searchAttributes(mart = ensembl, pattern = "GO")

go_attributes <- searchAttributes(mart = ensembl, pattern = "GO ") %>% pull(name) %>% .[-4]

```

# Read transcription factor databases

From <http://bioinfo.life.hust.edu.cn/AnimalTFDB/#!/>

Get GO annotations

```{r read-data}
tfs_db <- read_table2(file = 'http://bioinfo.life.hust.edu.cn/static/AnimalTFDB3/download/Homo_sapiens_TF') %>% 
            set_names(tolower(names(.))) %>% 
              rename(hgnc_symbol = "symbol") %>% 
                dplyr::select(-id)
# 1,665 TFs on 2020-11-25

## Transcription cofactors
tf_cofactors_db <- read_tsv("http://bioinfo.life.hust.edu.cn/static/AnimalTFDB3/download/Homo_sapiens_TF_cofactors") %>% 
                      set_names(tolower(names(.))) %>%
                        rename(hgnc_symbol = "symbol")
# 1,025 TF cofactors on 2020-11-25
```

# Get GO annotations {#get-go-annotations}

for all cell type-area marker genes

```{r fxn:getGO}
getGO <- function(genes = x) {
  
              getBM(attributes = c('hgnc_symbol', 'description', go_attributes), 
                    filters = 'hgnc_symbol', 
                    values = genes, 
                    mart = ensembl) %>%
    
              filter(! namespace_1003 %>% str_detect("cellular_component") &
                     ! name_1006 == '') %>% 
                add_count(name_1006) %>% arrange(desc(n), name_1006) %>% 
                  # mutate(name_1006 = as_factor(name_1006)) %>%
                    dplyr::select(hgnc_symbol, name_1006, n, description, everything())
}


getGO_map <- function(groups_tbl, celltype) {
    
    groups_tbl %>% 
    # dplyr::filter(item2 %>% str_detect(celltype)) %>% 
                dplyr::select(item2, genes) %>% 
                  pmap(~ tibble(group = ..1, 
                                go_df = list(getGO(genes = ..2))
                                )
                       ) %>%
                    reduce(bind_rows)
}
```