```{r}
wb.small <- read_rds("../data/wholebrain_v3_small68k.rds")
```


```{r}  
genes %>% lapply(featPlotHist(gene = ., seurat.object = wb.small)) %>% 
  plot_grid(plotlist = .)

fPlots <- list(featPlotHist(wb.small, cap = 3.8, begin = 0, alpha.grey = 0.3, alpha.group = 0.7),
               featPlotHist(gene = SATB2, wb.small, cap = 3.5, begin = 0, alpha.grey = 0.3, alpha.group = 0.7)
)

fPlots[[3]] <- featPlotHist(seurat.object = wb.small, gene = VIM, cap = 5.5)


cowplot::plot_grid(plotlist = fPlots)
```

```{r}
makePlot(gene = AQP4, cap = 4.5)

makePlot(gene = HES1, cap = 5)

makePlot(gene = PPP1R17, cap = 4)

makePlot(gene = FOXG1, cap = 3.25)

makePlot(gene = RBFOX3, cap = 2.7)

makePlot(gene = SST, cap = 5)
makePlot(gene = CALB2, cap = 4)
makePlot(gene = CCK, cap = 5.5)
```

# Whole brain: region markers by cell type
For each cell type, get the top marker genes for each area.

# Read-in cell-type/areal marker genes
```{r}
dir <- "~/Dropbox/2ndTrimester/tbls/wholebrain_celltype_area_markers/"
files <- paste0(dir, list.files(dir))

# Use read.delim bc 1st column is rownames (tidyr functions don't work)
markers <- lapply(files, read.delim)
```

For each cell type, get the top marker genes for each area.

## Astrocytes
```{r}
markers[[1]] %<>% separate(cluster, c("celltype", "area"))

markers[[1]] %<>% mutate(gene.ratio = pct.1 / pct.2,
                        gene.score = avg_logFC * gene.ratio)


# https://stackoverflow.com/a/27766224 slice_max

top.markers <- markers[[1]] %>% group_by(area) %>% slice_max(order_by = gene.score, n = 5)

fPlots$astro <- top.markers$gene %>% lapply(function(x) { makePlot(gene = !!sym(x), 
                                                         cap = 4)
}
)


# https://stackoverflow.com/questions/39736655/plot-over-multiple-pages

m1 <- marrangeGrob(fPlots$astro, nrow=4, ncol=5)
names(m1) <- seq(1:length(m1))

for(i in names(m1)) {
  ggsave(plot = m1[[i]], 
         filename = paste0("../out/astrocyte_markers_", i, ".png"),
         device = "png",
         width = 45, height = 30, units = "in")
}


grid_arrange
ggarrange()
```

## Neurons
```{r}
markers[[6]] %<>% separate(cluster, c("celltype", "area")) %>% 
                      mutate(gene.ratio = pct.1 / pct.2,
                             gene.score = avg_logFC * gene.ratio)

top.markers <- list()
top.markers$neurons <- markers[[6]] %>% 
                        group_by(area) %>% 
                          slice_max(order_by = gene.score, n = 5)

fPlots$neurons <- top.markers$neurons$gene %>% 
                    lapply(function(x) { 
                      
                      makePlot(gene = !!sym(x), 
                               cap = 4)
                    }
                    )

m1 <- list()
m1$neurons <- marrangeGrob(fPlots$neurons, nrow=4, ncol=5)

names(m1$neurons) <- seq(1:length(m1$neurons))

for(i in names(m1$neurons)) {
  ggsave(plot = m1$neurons[[i]], 
         filename = paste0("../out/neuron_markers_", i, ".png"),
         device = "png",
         width = 45, height = 30, units = "in")
}
```

## Radial glia
```{r}
markers[[9]] %<>% separate(cluster, c("celltype", "area")) %>% 
                      mutate(gene.ratio = pct.1 / pct.2,
                             gene.score = avg_logFC * gene.ratio)

top.markers <- list()
top.markers$rg <- markers[[9]] %>% 
                        group_by(area) %>% 
                          slice_max(order_by = gene.score, n = 5)

fPlots$rg <- top.markers$rg$gene %>% 
                    lapply(function(x) { 
                      
                      makePlot(gene = !!sym(x), 
                               cap = 4)
                    }
                    )

m1 <- list()
m1$rg <- marrangeGrob(fPlots$rg, nrow=4, ncol=5)

names(m1$rg) <- seq(1:length(m1$rg))

for(i in names(m1$rg)) {
  ggsave(plot = m1$rg[[i]], 
         filename = paste0("../out/radialglia_markers_", i, ".png"),
         device = "png",
         width = 45, height = 30, units = "in")
}
```

## Dividing
```{r}
df <- markers[[2]]
celltype <- "dividing"

df %>% separate(cluster, c("celltype", "area")) %>% 
                      mutate(gene.ratio = pct.1 / pct.2,
                             gene.score = avg_logFC * gene.ratio)

top.markers <- list()
top.markers[[celltype]] <- markers[[9]] %>% 
                        group_by(area) %>% 
                          slice_max(order_by = gene.score, n = 5)

fPlots$rg <- top.markers$rg$gene %>% 
                    lapply(function(x) { 
                      
                      makePlot(gene = !!sym(x), 
                               cap = 4)
                    }
                    )

m1 <- list()
m1$rg <- marrangeGrob(fPlots$rg, nrow=4, ncol=5)

names(m1$rg) <- seq(1:length(m1$rg))

for(i in names(m1$rg)) {
  ggsave(plot = m1$rg[[i]], 
         filename = paste0("../out/radialglia_markers_", i, ".png"),
         device = "png",
         width = 45, height = 30, units = "in")
}
```

```{r}
p_load(cowplot)

featPlotHist(wb.small, cap = 3.9, begin = 0, alpha.grey = 0.3, alpha.group = 0.5)

wb.small@assays$RNA@data["SOX2", ] %>% as.data.frame() %>% setNames("SOX2")
```
```

