---
title: "Constellation Plots" 
params:
  cells.cl.df: NULL # s.obj@meta.data
  groups.col: NULL  # character, name of column to group by
  rd.dat: list()
  colors.use : c()
  cl: NULL
  cl.numeric: NULL
  n.pcs: 20,
  run.knn: TRUE
  k: 15,
  frac.th: 0.05,
  cl.df: NULL
  out.dir: '../out'
---

```{r}
library(tidyverse, magrittr)

cl <- params$cl
cl.df <- params$cl.df
cells.cl.df <- params$cells.cl.df
groups.col <- params$groups.col
rd.dat <- params$rd.dat
colors.use <- params$colors.use
cl.numeric <- params$cl.numeric
n.pcs <- params$n.pcs
k <- params$k
out.dir <- params$out.dir
frac.th <- params$frac.th
run.knn <- params$run.knn
```

Extra functions
```{r functions}
.env <- new.env()

.env$source_rmd <- function(file, local = FALSE, ...){
  options(knitr.duplicate.label = 'allow')

  tempR <- tempfile(tmpdir = ".", fileext = ".R")
  on.exit(unlink(tempR))
  knitr::purl(file, output = tempR, quiet = TRUE)

  envir <- globalenv()
  source(tempR, local = envir, ...)
}

.env$reactable <- function(...) {
  htmltools::tagList(reactable::reactable(...))
}

# source("../../../code_general/setup_R_session_CSE.R")

attach(.env)

source_rmd("scrattch.hicat_fxns.Rmd")
```

# 1. Build dataframes for constellation plots.

1
```{r cl, eval=TRUE, include=TRUE}

# Cluster, or area-celltype combination.
cl <- cells.cl.df[[groups.col]] %>% as.factor %>% 
  set_names(cells.cl.df$cell.name)
# 128 clusters in all _combo2_ cells
# 77 clusters in all _combo2_ & ExN lineage cells.

cl.numeric <- as.numeric(cl) %>% set_names(value = names(cl))
```

2
```{r cl.df, eval=TRUE, include=TRUE}

cl.df <- get_cl_df(cl)

cl.df$area <- str_split_fixed(cl.df$cluster_label, "-", 2)[ ,2] %>% tolower 

cl.df$clade <- str_split_fixed(cl.df$cluster_label, "-", 2)[ ,1] %>% tolower 
# Add clade_id, clade_color to cl.df
# cl.df <- cl.df %>% left_join(clade.cols)


cl.df <- cl.df %>% left_join(colors.use) 
# %>%  rename(cluster_color = "colors.use")
# rm(group.cols)

# cells.cl.df: Add cluster_id column from cl.df; remove unused columns. 
cells.cl.df <- left_join(cells.cl.df,
                         # %>% select(cell.name, groups.col, combined.cluster.2),
                         cl.df, by = 'cluster_label') %>%
                         
                         # Requires cells.cl.df (metadata) to have column being used for groups
                         # named 'cluster_label' to match with cl_df during join.
                 mutate(cluster_id = as.factor(cluster_id))
```

# 4 Find cluster centers from UMAP coordinates
```{r rd.cl.center}

rd.cl.center <- get_RD_cl_center(rd.dat = rd.dat$umap, cl)
message("Got rd.cl.center")
```

```{r update-rd.cl.center}
rd.cl.center %<>% 
  as.data.frame %>% 
  set_names(c("x", "y")) %>%
  add_column(cl = cl.df$cluster_id, .before = "x") %>%
  # add_column preserves rownames.
  # but moving rownames to column cluster_label anyway bc of left_join below.
  rownames_to_column("cluster_label")

message("Updated rd.cl.center")
```

5 Join `cl.df` and `rd.cl.center` into `cl.center.df` for input into `get_KNN_graph`.
```{r cl.center.df}
cl.center.df <- left_join(rd.cl.center, cl.df,
                          by = c("cluster_label")) 
```

# 6 Get knn and cluster counts
# Calls `knn.cl` in scrattch.hicat_fxns.Rmd`
```{r knn.result}
if(run.knn == TRUE) {

knn.result <- RANN::nn2(data = rd.dat$pca[, 1:n.pcs], k = k)

}else{knn.result <- knn.result}
```


```{r knn.cl}
cl.numeric <- as.numeric(cl) %>% set_names(value = names(cl))
# Can also be passed as a param to the Rmd.

knn.cl <- get_knn_graph(rd.dat = rd.dat$umap, 
                        cl.df =  cl.df, 
                        cl = cl.numeric, 
                        knn.outlier.th = 2, outlier.frac.t = 0.5)

# rm(rd.dat, ncx.clusters)
```

# 2. Make constellation plot
```{r knn_cl_df_filter}

# Keep only cells whose $frac (fraction of cells in cluster with nearest neighbors in a different cluster) >= 0.05.
# Defined in `get_knn_graph`: 
# knn.cl.df$frac = knn.cl.df$Freq / knn.cl.df$cl.from.total
# 10% : 213 edges
knn.cl.df.filter <- knn.cl$knn.cl.df %>% dplyr::filter(frac >= frac.th)

# cl.to, cl.from numeric or factor?
# Need to be numeric for getting the rows where cl.to == cl.from (knn.cl.df$same)
knn.cl.df.filter %<>% mutate(cl.from = as.numeric(cl.from), cl.to = as.numeric(cl.to))
```

```{r plot-constellation}
# Plot only edges between ExN lineage clusters.
# knn.cl.df %<>% filter_at(vars(cl.from.label, cl.to.label), 
#                        all_vars(str_detect(., "RG|IPC|Neuron|OPC|Dividing"))
#              )

# cl.center.df$cluster_label %<>% str_remove("_combo2")

cl.plot <- plot_constellation(knn.cl.df = knn.cl.df.filter, 
                              cl.center.df = cl.center.df, 
                              out.dir = out.dir,
                              node.label = "cluster_label",  # name of column in cl.center.df with cluster/node names
                              exxageration = 0.4, curved = TRUE, 
                              plot.parts = FALSE, plot.hull = NULL, 
                              plot.height = 40, plot.width = 40,
                              node.dodge = TRUE, 
                              label.size = 1.5, max_size = 25)

```
