---
title: 'Constellation Plots: Neocortex Excitatory: Cell Types by Area'
date: 2020-12-22
output: html_document
---

2020-12-22: Trying to find the quantification stuff for neocortex by areas for paper figure.

```{r}


# wholebrain
load('/home/csandoval/cse-phd/second-trimester/neocortex/constellation_plots/out_intermediate/intermediate_objects_constellationPlots.RData')

load('../../data/exn_lineage/ncx.exn_gw16_gw19_2_v3.RData') # only neurons, ipcs and rg
rm(ncx.exn, seurat.object)
```

## 2. Make constellation plot. {data-link="2. Make constellation plot."}

Call `buildConstellation.Rmd`, which has all the steps required to make dfs and plot. Takes
arguments: `cells.cl.df`, `groups.col`, `colors.use` and `rd.dat`.

```{r call-buildConstellationPlot}

# Neocortex excitatory (271k) used originally to make the cell types by area constellation plot.
# This object was saved when making the cell types by cluster plot,
# but has everything we need to make dfs.
x <- read_rds('.../neocortex/constellation_plots/out_intermediate/
              dfs_and_objects_for_constellationPlot_ncx_exn.rds') # by clusters

names(x) <- c('cells_cl_df', 'cluster_colors', 'cl', 'cl_numeric', 'cl_center_df', 'reductions')

x$cluster_colors %<>% rename(clade = 'celltype')
x$cells_cl_df %<>% select(-cl_id, -cluster_label) %<>% 
  rename(cluster_label = 'cell.type.area')

cells$cl.numeric <- as.numeric(cells$cl) %>% set_names(value = names(cells$cl))

rmarkdown::render(input = "./buildConstellation.Rmd", 
                  params = list(cells.cl.df = x$cells_cl_df, 
                                rd.dat = x$reductions, 
                                groups.col = "cluster_label", # renamed from cell.type.area 
                                colors.use = x$cluster_colors,
                                n.pcs = 20,
                                run.knn = FALSE,
                                k = 15,
                                out.dir = '../out'
                                # cl = x$cl,
                                # cl.numeric = x$cl_numeric)
))

2020-12-22 NEXT: Make own cl.numeric for this plot and pass to buildConstellation as parameter.
done - try running knn.cl.dat or whatever the next block is (not run knn again)

rd.dat <- x$reductions                               
groups.col <- 'cluster_label'
colors.use <- colors.clade %<>% 
 
rm(cells.cl.df, rd.dat, groups.col, colors.use)


  cells.cl.df: cells.cl.df # s.obj@meta.data                     
  groups.col: ""  # character, name of column to group by
  rd.dat: list()
  colors.use : c()
  cl: NULL
  cl.numeric: NULL
  n.pcs: NULL,
  run.knn: NULL
  k: NUL,
  frac.th: NULL,
  cl.df: NULL)
                  )
```
