---
title: "Split Sankey Plots"
date: 2010-11-02
output: html_notebook
---

From @sankey_plots.Rmd\
{r 2020-10-21_normalizePairCounts}

```{r}
sankey_counts <- read_rds("../intermediate_files/sankey_markers_pairs_exnLineage.rds")

load("../../../../area_specific_markers/sankey/R/2020-10-26_sankey_plots.RData")
```

```{r}
colors.area
```

Split `givis.df` into stages.
```{r split_givsdf_stages}

stages <- levels(gvis.df$df[[1]]$stage.source)
# early #mid #late
 

gvis.df_split_stage <- map2(.x = gvis.df$df$df,
                            .y = gvis.df$df$comparison,
                             .f = function(df = .x, comparison = .y, stage = stages) {
                                      map(.x = stage,
                                           .f = ~filter(df,
                                                        stage.source == .x & stage.target == .x)
                                              ) %>% tibble(comparison = comparison, stage = stages, split_df = .)
                               }
                           )                 
                                                  
                               
                  
gvis.df_split_stage %<>% purrr::reduce(rbind)
```

```{r}
library(pacman)
p_load(magrittr)
p_load(googleVis)
p_load(glue)

getwd()
path <- "~/cse-phd/second-trimester/neocortex/markers_area_celltype/sankey_plots/out/split_by_stage/sankey_"

sankey_inter_celltype_split_stage <- pmap(gvis.df_split_stage,
                                          .f = ~ make_gvisSankey(chart_id = paste(..1, ..2, sep = "_"), 
                                                                 gvis_df_x = ungroup(..3)
                                                                 )
)

gvis.df_split_stage$sankey_plot <- sankey_inter_celltype_split_stage %>% map(~.[[4]])


sankey_inter_celltype_split_stage[[1]][[1]] %>% purrr::flatten() %>% map() map(~ .$chart_id[1]) %>% print(tag = "chart", file = glue(path, chart_id, ".html"))
  
  
  glue(path, chart_id, ".html")
  
sankey_inter_celltype_split_stage %>% map_depth(~ print(.$chart_id[[4]], tag = "chart",
                                                        file = glue(path, chart_id, ".html"),
                                                  ), 
                                                .depth = 2)
```


